/* Sistema de E-commerce - Firebird 3.0+ */

CREATE DATABASE 'ecommerce.fdb'
    USER 'SYSDBA' PASSWORD 'masterkey'
    DEFAULT CHARACTER SET UTF8;

CONNECT 'ecommerce.fdb' USER 'SYSDBA' PASSWORD 'masterkey';


CREATE TABLE cliente (
    id_cliente      INTEGER         GENERATED BY DEFAULT AS IDENTITY,
    nome            VARCHAR(100)    NOT NULL,
    cpf             CHAR(11)        NOT NULL,
    email           VARCHAR(100)    NOT NULL,
    senha           VARCHAR(255)    NOT NULL,
    telefone        VARCHAR(20),
    data_cadastro   TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT pk_cliente       PRIMARY KEY (id_cliente),
    CONSTRAINT uk_cliente_cpf   UNIQUE (cpf),
    CONSTRAINT uk_cliente_email UNIQUE (email)
);


CREATE TABLE endereco (
    id_endereco     INTEGER         GENERATED BY DEFAULT AS IDENTITY,
    id_cliente      INTEGER         NOT NULL,
    logradouro      VARCHAR(150)    NOT NULL,
    numero          VARCHAR(10)     NOT NULL,
    complemento     VARCHAR(50),
    bairro          VARCHAR(80)     NOT NULL,
    cidade          VARCHAR(80)     NOT NULL,
    uf              CHAR(2)         NOT NULL,
    cep             CHAR(8)         NOT NULL,

    CONSTRAINT pk_endereco PRIMARY KEY (id_endereco),
    CONSTRAINT fk_endereco_cliente
        FOREIGN KEY (id_cliente)
        REFERENCES cliente (id_cliente)
        ON UPDATE CASCADE
        ON DELETE NO ACTION
);


CREATE TABLE categoria (
    id_categoria    INTEGER         GENERATED BY DEFAULT AS IDENTITY,
    nome            VARCHAR(80)     NOT NULL,
    descricao       VARCHAR(255),

    CONSTRAINT pk_categoria      PRIMARY KEY (id_categoria),
    CONSTRAINT uk_categoria_nome UNIQUE (nome)
);


CREATE TABLE produto (
    id_produto      INTEGER         GENERATED BY DEFAULT AS IDENTITY,
    nome            VARCHAR(150)    NOT NULL,
    descricao       BLOB SUB_TYPE TEXT,
    preco           DECIMAL(10,2)   NOT NULL,
    estoque         INTEGER         DEFAULT 0 NOT NULL,
    data_cadastro   TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ativo           BOOLEAN         DEFAULT TRUE NOT NULL,

    CONSTRAINT pk_produto         PRIMARY KEY (id_produto),
    CONSTRAINT ck_produto_preco   CHECK (preco >= 0),
    CONSTRAINT ck_produto_estoque CHECK (estoque >= 0)
);


/* Tabela associativa que resolve o N:N entre produto e categoria */
CREATE TABLE produto_categoria (
    id_produto      INTEGER         NOT NULL,
    id_categoria    INTEGER         NOT NULL,

    CONSTRAINT pk_produto_categoria PRIMARY KEY (id_produto, id_categoria),
    CONSTRAINT fk_pc_produto
        FOREIGN KEY (id_produto)
        REFERENCES produto (id_produto)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT fk_pc_categoria
        FOREIGN KEY (id_categoria)
        REFERENCES categoria (id_categoria)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);


CREATE TABLE pedido (
    id_pedido       INTEGER         GENERATED BY DEFAULT AS IDENTITY,
    id_cliente      INTEGER         NOT NULL,
    id_endereco     INTEGER         NOT NULL,
    data_pedido     TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    status          VARCHAR(20)     DEFAULT 'pendente' NOT NULL,
    valor_total     DECIMAL(10,2)   DEFAULT 0 NOT NULL,

    CONSTRAINT pk_pedido PRIMARY KEY (id_pedido),
    CONSTRAINT fk_pedido_cliente
        FOREIGN KEY (id_cliente)
        REFERENCES cliente (id_cliente)
        ON UPDATE CASCADE
        ON DELETE NO ACTION,
    CONSTRAINT fk_pedido_endereco
        FOREIGN KEY (id_endereco)
        REFERENCES endereco (id_endereco)
        ON UPDATE CASCADE
        ON DELETE NO ACTION,
    CONSTRAINT ck_pedido_status
        CHECK (status IN ('pendente','pago','enviado','entregue','cancelado')),
    CONSTRAINT ck_pedido_valor
        CHECK (valor_total >= 0)
);


/* preco_unitario é congelado no momento da compra para preservar histórico */
CREATE TABLE item_pedido (
    id_item         INTEGER         GENERATED BY DEFAULT AS IDENTITY,
    id_pedido       INTEGER         NOT NULL,
    id_produto      INTEGER         NOT NULL,
    quantidade      INTEGER         NOT NULL,
    preco_unitario  DECIMAL(10,2)   NOT NULL,
    subtotal        DECIMAL(10,2)   NOT NULL,

    CONSTRAINT pk_item_pedido PRIMARY KEY (id_item),
    CONSTRAINT fk_item_pedido
        FOREIGN KEY (id_pedido)
        REFERENCES pedido (id_pedido)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT fk_item_produto
        FOREIGN KEY (id_produto)
        REFERENCES produto (id_produto)
        ON UPDATE CASCADE
        ON DELETE NO ACTION,
    CONSTRAINT ck_item_quantidade CHECK (quantidade > 0),
    CONSTRAINT ck_item_preco      CHECK (preco_unitario >= 0),
    CONSTRAINT ck_item_subtotal   CHECK (subtotal >= 0)
);


/* 1:N com pedido permite pagamento dividido em múltiplas formas */
CREATE TABLE pagamento (
    id_pagamento    INTEGER         GENERATED BY DEFAULT AS IDENTITY,
    id_pedido       INTEGER         NOT NULL,
    forma_pagamento VARCHAR(30)     NOT NULL,
    valor           DECIMAL(10,2)   NOT NULL,
    status          VARCHAR(20)     DEFAULT 'pendente' NOT NULL,
    data_pagamento  TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT pk_pagamento PRIMARY KEY (id_pagamento),
    CONSTRAINT fk_pagamento_pedido
        FOREIGN KEY (id_pedido)
        REFERENCES pedido (id_pedido)
        ON UPDATE CASCADE
        ON DELETE NO ACTION,
    CONSTRAINT ck_pagamento_forma
        CHECK (forma_pagamento IN ('cartao_credito','cartao_debito','pix','boleto','vale_presente')),
    CONSTRAINT ck_pagamento_status
        CHECK (status IN ('pendente','aprovado','recusado','estornado')),
    CONSTRAINT ck_pagamento_valor
        CHECK (valor > 0)
);


/* UNIQUE em id_item garante 1:1: somente quem comprou pode avaliar, uma única vez */
CREATE TABLE avaliacao (
    id_avaliacao    INTEGER         GENERATED BY DEFAULT AS IDENTITY,
    id_item         INTEGER         NOT NULL,
    nota            INTEGER         NOT NULL,
    comentario      BLOB SUB_TYPE TEXT,
    data_avaliacao  TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT pk_avaliacao      PRIMARY KEY (id_avaliacao),
    CONSTRAINT uk_avaliacao_item UNIQUE (id_item),
    CONSTRAINT fk_avaliacao_item
        FOREIGN KEY (id_item)
        REFERENCES item_pedido (id_item)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT ck_avaliacao_nota CHECK (nota BETWEEN 1 AND 5)
);


/* Índices para acelerar consultas frequentes */
CREATE INDEX idx_endereco_cliente   ON endereco   (id_cliente);
CREATE INDEX idx_pedido_cliente     ON pedido     (id_cliente);
CREATE INDEX idx_pedido_endereco    ON pedido     (id_endereco);
CREATE INDEX idx_pedido_status      ON pedido     (status);
CREATE INDEX idx_pedido_data        ON pedido     (data_pedido);
CREATE INDEX idx_item_pedido_ped    ON item_pedido(id_pedido);
CREATE INDEX idx_item_pedido_pro    ON item_pedido(id_produto);
CREATE INDEX idx_pagamento_pedido   ON pagamento  (id_pedido);
CREATE INDEX idx_pagamento_status   ON pagamento  (status);
CREATE INDEX idx_produto_ativo      ON produto    (ativo);


COMMIT;


/* Dados de exemplo */

INSERT INTO cliente (nome, cpf, email, senha, telefone) VALUES ('Maria Silva',  '12345678901', 'maria@email.com', 'hash_senha_1', '74999990001');
INSERT INTO cliente (nome, cpf, email, senha, telefone) VALUES ('João Pereira', '23456789012', 'joao@email.com',  'hash_senha_2', '74999990002');
INSERT INTO cliente (nome, cpf, email, senha, telefone) VALUES ('Ana Souza',    '34567890123', 'ana@email.com',   'hash_senha_3', '74999990003');

INSERT INTO endereco (id_cliente, logradouro, numero, complemento, bairro, cidade, uf, cep) VALUES (1, 'Rua das Acácias',   '123', 'Apto 101', 'Centro',       'Petrolina', 'PE', '56300000');
INSERT INTO endereco (id_cliente, logradouro, numero, complemento, bairro, cidade, uf, cep) VALUES (1, 'Av. das Palmeiras', '456', NULL,       'Areia Branca', 'Petrolina', 'PE', '56310000');
INSERT INTO endereco (id_cliente, logradouro, numero, complemento, bairro, cidade, uf, cep) VALUES (2, 'Rua dos Ipês',      '78',  NULL,       'Vila Eduardo', 'Petrolina', 'PE', '56320000');
INSERT INTO endereco (id_cliente, logradouro, numero, complemento, bairro, cidade, uf, cep) VALUES (3, 'Rua do Sol',        '999', 'Casa B',   'Cohab',        'Juazeiro',  'BA', '48900000');

INSERT INTO categoria (nome, descricao) VALUES ('Eletrônicos', 'Aparelhos eletrônicos em geral');
INSERT INTO categoria (nome, descricao) VALUES ('Informática', 'Computadores, periféricos e acessórios');
INSERT INTO categoria (nome, descricao) VALUES ('Áudio',       'Fones, caixas de som e equipamentos de áudio');
INSERT INTO categoria (nome, descricao) VALUES ('Livros',      'Livros físicos e digitais');

INSERT INTO produto (nome, descricao, preco, estoque) VALUES ('Notebook Acer Aspire 5',   'Notebook 15.6", i5, 8GB RAM, 256GB SSD',    3499.90, 15);
INSERT INTO produto (nome, descricao, preco, estoque) VALUES ('Fone Bluetooth JBL T520',  'Fone over-ear com cancelamento de ruído',    349.90, 50);
INSERT INTO produto (nome, descricao, preco, estoque) VALUES ('Mouse Logitech MX Master', 'Mouse sem fio ergonômico',                   599.00, 30);
INSERT INTO produto (nome, descricao, preco, estoque) VALUES ('Livro: Banco de Dados',    'Sistemas de banco de dados - Elmasri',       189.50, 20);

INSERT INTO produto_categoria (id_produto, id_categoria) VALUES (1, 1);
INSERT INTO produto_categoria (id_produto, id_categoria) VALUES (1, 2);
INSERT INTO produto_categoria (id_produto, id_categoria) VALUES (2, 1);
INSERT INTO produto_categoria (id_produto, id_categoria) VALUES (2, 3);
INSERT INTO produto_categoria (id_produto, id_categoria) VALUES (3, 1);
INSERT INTO produto_categoria (id_produto, id_categoria) VALUES (3, 2);
INSERT INTO produto_categoria (id_produto, id_categoria) VALUES (4, 4);

INSERT INTO pedido (id_cliente, id_endereco, status, valor_total) VALUES (1, 1, 'pago',     3849.80);
INSERT INTO pedido (id_cliente, id_endereco, status, valor_total) VALUES (2, 3, 'enviado',   599.00);
INSERT INTO pedido (id_cliente, id_endereco, status, valor_total) VALUES (3, 4, 'pendente',  189.50);

INSERT INTO item_pedido (id_pedido, id_produto, quantidade, preco_unitario, subtotal) VALUES (1, 1, 1, 3499.90, 3499.90);
INSERT INTO item_pedido (id_pedido, id_produto, quantidade, preco_unitario, subtotal) VALUES (1, 2, 1,  349.90,  349.90);
INSERT INTO item_pedido (id_pedido, id_produto, quantidade, preco_unitario, subtotal) VALUES (2, 3, 1,  599.00,  599.00);
INSERT INTO item_pedido (id_pedido, id_produto, quantidade, preco_unitario, subtotal) VALUES (3, 4, 1,  189.50,  189.50);

INSERT INTO pagamento (id_pedido, forma_pagamento, valor, status) VALUES (1, 'cartao_credito', 3000.00, 'aprovado');
INSERT INTO pagamento (id_pedido, forma_pagamento, valor, status) VALUES (1, 'pix',             849.80, 'aprovado');
INSERT INTO pagamento (id_pedido, forma_pagamento, valor, status) VALUES (2, 'cartao_credito',  599.00, 'aprovado');
INSERT INTO pagamento (id_pedido, forma_pagamento, valor, status) VALUES (3, 'boleto',          189.50, 'pendente');

INSERT INTO avaliacao (id_item, nota, comentario) VALUES (1, 5, 'Excelente notebook, entrega rápida.');
INSERT INTO avaliacao (id_item, nota, comentario) VALUES (2, 4, 'Bom fone, mas a bateria poderia durar mais.');

COMMIT;